### PR TITLE
Handle fatal runtime errors

### LINKED ISSUE #954: Should raise fatal error if javascript recursion error occurs
If I say:
`import sys; sys.setrecursionlimit(100000); def f(): return 1 + f(); f()`
on native python, the result is `Segmentation fault` and the OS kills Python. This is the correct behavior. Pyodide should also raise a fatal error and refuse to evaluate further code. This should prevent people from getting confused (see discussion in #917, #951).

### LINKED ISSUE #1005: Detecting crashes of the Pyodide WASM environment
Copied from:
https://github.com/iodide-project/iodide/issues/994

> It would be very useful if Iodide could detect when Pyodide WASM environment crashes (e.g. after a segfault), and warn the user.
> 
> For instance, running the simple code snippet from iodide-project/pyodide#200 in the demo notebook https://iodide.io/pyodide-demo/python.html produces a segfault which crashes Pyodide, meaning that any subsequent command will also fail.
> 
> This situation is very confusing for users, because Iodide still works in this scenario. So the user gets some error in one notebook cell, and then thinking that maybe something was wrong in the provided code, they would try to change the input code, but irrespective of the input the cell would still fail. More frustrating, even other cells that used to work now will also fail. The only solution is to restart the page.
> 
> Even if though segfaults shouldn't happen, it's still possible to run into one, particularly when people build some custom packages. I'm not sure if running out of memory can also produce a somewhat similar outcome.

### PR DESCRIPTION
**Pull request by hoodmane**
This resolves #954 and resolves #1005.

### CODE REVIEW

File: src/pyodide.js [hunk 1]
```diff
@@ -336,6 +337,27 @@ globalThis.languagePluginLoader = new Promise((resolve, reject) => {
...
+      }
+      // Have to do this case first because typeof(some_pyproxy) === "function".
+      if (Module.PyProxy.isPyProxy(value)) {
+        value.destroy();
+        continue;
+      }
+      if (typeof (value) === "function") {
+        Module.public_api[key] = function() {
+          throw Error("Pyodide has suffered a fatal error, refresh the page. " +
+                      "Please report this to the Pyodide maintainers.");
```
Comment (phorward) [inline src/pyodide.js:354]: This will mean: A lot of new tickets ;-)

**Review by phorward — APPROVED** [review]
I think this looks good and cleans up the code in some places.

**Comment by hoodmane** [comment]
Thanks for the review @phorward.

> This will mean: A lot of new tickets ;-)

Yeah I'm really curious to learn any new ways to trigger this. I currently know exactly two ways: one is issue #200 which is an emscripten bug:
```python
import os
os.listdir('/proc/self/fd')
```
The other is with recursion:
```python
def f(): f()
f()
```
which happens because `setRecursionLimit` isn't conservative enough when it sets the Python recursion limit (issue #821 / #951).
