### PR TITLE
Fix #291: Allow loading of arbitrary packages

### LINKED ISSUE #291: Loading an unknown package from a custom URL
As discussed in https://github.com/iodide-project/pyodide/pull/286,

by @madhur-tandon 
> The URL generated is correct and this issue is not related to it. The reason that it doesn't work without adding it to packages.json file is because the function load_package is defined that way. It checks if the package we are trying to load is present in this file, else, it returns the error of Unknown package 'numpy-broken'

and @mdboom 

>  I thought if you provided a URL, it wouldn't try to do the dependency resolution using packages.json. @rth: Is that how that's supposed to work? How does one load a completely unknown package?

### PR DESCRIPTION
**Pull request by mdboom**
This allows unknown packages to fall through to load as URLs.  If loading those URLs happens to fail, rather than causing all other packages to fail, it removes that broken package from the list of things that eventually gets added to `loadedPackages`, and calls `monitorRunDependecies` twice to simulate a package loading.

Cc: @madhur-tandon

### CODE REVIEW

File: src/pyodide.js [hunk 1]
```diff
@@ -176,7 +175,19 @@ var languagePluginLoader = new Promise((resolve, reject) => {
...
+          // the package from toLoad so we don't mark it as loaded.
+          console.log(`Couldn't load package from URL ${script.src}`)
+          let index = toLoad.indexOf(package);
+          if (index !== -1) {
+            toLoad.splice(index, 1);
+          }
+          for (let i = 0; i < 2; i++) {
+            window.pyodide._module.monitorRunDependencies();
+          }
+        };
```
Comment (madhur-tandon) [inline src/pyodide.js]: I think this seems fine and it should work. I will still test it out manually by running ``./bin/pyodide serve`` and let you know. However, 
- a) Shouldn't ``console.log`` be ``console.error`` instead? 

- b) Note that we might end up using ``window.onerror`` too as seen in the PR for ABI numbers here: https://github.com/iodide-project/pyodide/pull/286 

[specifically, ``https://github.com/iodide-project/pyodide/blob/43339d9880387a09f73e0afd139ea8a400107480/src/pyodide.js#L180``] 

so as to avoid waiting forever for the promise to be fulfilled, do we also use the same snippet as used here inside ``window.onerror`` too? If yes, maybe we could create a separate function for the snippet and call it inside both ``script.onerror`` and ``window.onerror``?

What do you think?

File: src/pyodide.js [hunk 2]
```diff
@@ -120,7 +120,6 @@ var languagePluginLoader = new Promise((resolve, reject) => {
           });
         } else {
           console.error(`Unknown package '${package}'`);
```
Comment (rth) [inline src/pyodide.js]: I imagine this will not fully work if we attempt to a list of remote URLs as input (or a mixture or packages and URLs)? 

If it is the case maybe we can merge this and leave the parent issue open after updating the status? or some decide on some other way of handling this.

Comment (mdboom) [reply src/pyodide.js]: @rth: Why do you say that?

File: src/pyodide.js (hunk 1 above)
Comment (mdboom) [reply src/pyodide.js]: > a) Shouldn't console.log be console.error instead?

Sure.  That makes sense.

> b) Note that we might end up using window.onerror too as seen in the PR for ABI numbers here: #286

That would have us handling every error that the window could throw (and there are a lot of them) as if it was a package failing to load.  I don't think that makes sense.

> so as to avoid waiting forever for the promise to be fulfilled, do we also use the same snippet as used here inside window.onerror too?

It would be up to the caller to handle the promise timing out and deciding what to do.  Which this change, if a package fails to load (because the URL is a 404, or the URL times out) or if it loads but there's an error in it, the counter will tick down and the promise will eventually finish.

But maybe I'm misunderstanding you.  Could you be more specific?

File: src/pyodide.js (hunk 2 above)
Comment (rth) [reply src/pyodide.js]: Sorry I misread it for `throw <error>` which would have interrupted the while loop. Nevermind.

Comment (mdboom) [reply src/pyodide.js]: No problem.  Thanks for the review.

File: src/pyodide.js (hunk 1 above)
Comment (madhur-tandon) [reply src/pyodide.js]: This is probably not urgent right now and we can address it in the PR for ABI numbers https://github.com/iodide-project/pyodide/pull/286 if at all the need be.
